
#
# Dit bestand bevat configuratie-instellingen om je site aan te passen
#

# Naam van je site (weergegeven in de header)
name: Arend en Ole

# Korte bio of beschrijving (weergegeven in de header)
description: "Meest gestoorde blog ooit! Verhalen die je nooit zult vergeten. Inclusief video's, foto's, en soms exposes!"

# URL van je avatar of profielfoto
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

#
# Optionele instellingen
#

# Links voor sociale media in de footer
footer-links:
  github: bombataeter4 # Jouw GitHub-gebruikersnaam
  twitter: jekyllrb # Pas dit aan naar je eigen Twitter-gebruikersnaam
  instagram:
  youtube: channel/<your_channel_id> # Vervang met jouw YouTube-kanaal
  rss: true # Zet dit op true om een werkend RSS-icoon te tonen

# Disqus shortname voor reacties (als je Disqus gebruikt)
disqus: # Voeg je Disqus-shortname hier toe

# Google Analytics tracking code
google_analytics: # Voeg je Google Analytics tracking-ID toe, bijvoorbeeld UA-XXXXXXXXX-X

# URL van je website (voor Sitemap.xml en RSS-feed)
url: "https://bombataeter4.github.io"

# Base URL (voor projectpagina's, laat leeg als je een gebruikerspagina maakt)
baseurl: "" # Voor een site op een gebruikersdomein, zoals bombataeter4.github.io

# Permalinkstructuur voor je blogposts
permalink: /:title/

#
# Technische instellingen (verander deze alleen als je weet wat je doet)
#

# Versie van Jekyll Now die je gebruikt
version: v1.2.0

# Markdown-instellingen
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Sass-instellingen
sass:
  style: :expanded

# Plug-ins die worden gebruikt
plugins:
  - jekyll-sitemap # Voor een sitemap
  - jekyll-feed # Voor een Atom-feed

# Bestanden die worden uitgesloten uit de productie
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

